#!/bin/bash

BRANCH=trunk

if [ -n "$1" ]; then
    case $1 in
        1.1)
            BRANCH=branches/1.1;;
        2.0)
            BRANCH=trunk;;
        trunk)
            BRANCH=trunk;;
        *)
            echo "Unknown branch $1"
            exit 1
            ;;
    esac
fi

SVN=/home/gauvain/svn/ovd
OVD=$SVN/$BRANCH
SPECS=/home/gauvain/rpmbuild/SPECS
SOURCES=/home/gauvain/rpmbuild/SOURCES

rm -rf $(find /home/gauvain/rpmbuild/ | grep ovd)

cd $SVN
svn up

cd $OVD

set -x

cd $OVD/SessionManager
rm -f ovd-session-manager*.tar.gz
./autogen.sh && make && make distcheck
cp ovd-session-manager*.tar.gz $SOURCES
cp ovd-session-manager.spec $SPECS

cd $OVD/ApplicationServer
rm -f ovd-application-server*.tar.gz
./autogen.sh && make && make distcheck
cp ovd-application-server*.tar.gz $SOURCES
cp ovd-application-server.spec $SPECS

set +e
cd $SPECS
for spec in $(ls ovd*spec); do
    rpmbuild "-ba --sign --buildroot /tmp/rpmbuild $spec"
done

appletsrpm

exit 0
